name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Next package version. patch, minor, major or specific version.
        required: true
        default: patch

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build package
        run: yarn build
      - name: Update package version
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          yarn release $VERSION
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Publish
        run: |
          npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
          npm publish ./eslint-plugin-sonar
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
